# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=250)),
                ('fecha_constitucion', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('pasaporte', models.CharField(max_length=15, null=True)),
                ('nombres', models.CharField(max_length=250)),
                ('apellido_paterno', models.CharField(max_length=250)),
                ('apellido_materno', models.CharField(max_length=250, null=True)),
                ('sexo', models.SmallIntegerField(choices=[(0, 'Masculino'), (1, 'Femenino')])),
                ('fecha_nacimiento', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo',
            field=models.SmallIntegerField(choices=[(1, 'Persona juridica'), (0, 'Persona natural')]),
        ),
        migrations.AddField(
            model_name='personanatural',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
    ]
