# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20170508_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nombre_comercial',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ruc',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
