# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_abreviado', models.CharField(max_length=30)),
                ('requisitos', models.TextField(max_length=200, null=True)),
                ('responsabilidades', models.TextField(max_length=200, null=True)),
                ('tipo', models.SmallIntegerField(choices=[(0, 'Funcional'), (1, 'Corporativo'), (2, 'Operativo')], null=True)),
            ],
        ),
    ]
