# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0004_auto_20170531_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='coordenadas',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='longitud',
        ),
    ]
