# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        ('persona', '0003_auto_20170508_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.SmallIntegerField(choices=[(0, 'Activo'), (1, 'Inactivo')], default=0)),
                ('observaciones', models.TextField(max_length=2000, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.PersonaNatural')),
            ],
        ),
        migrations.CreateModel(
            name='PlazaTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_puestos', models.IntegerField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.Cargo')),
            ],
        ),
    ]
