# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'permissions': (('genera_nomina', 'Puede generar la nómina'),)},
        ),
        migrations.AddField(
            model_name='empleado',
            name='plazas_trabajo',
            field=models.ManyToManyField(to='empleado.PlazaTrabajo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
