# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 19:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_empleado_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='plazatrabajo',
            name='coordenadas',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='plazatrabajo',
            name='latitud',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='plazatrabajo',
            name='longitud',
            field=models.FloatField(default=0, null=True),
        ),
    ]
